-- A challenge: one practice chart somebody finished, turned into a short link a friend can play.
--
-- The chart is addressed the way a round token addresses it — asset, timeframe, start_index —
-- so nothing about the candles is copied here. creator_correct comes from a result token the
-- server signed when the creator's chart ended, never from the client, which is what stops a
-- challenge advertising a score nobody made.
--
-- creator_id is nullable: an anonymous player can challenge a friend too. ON DELETE SET NULL,
-- not CASCADE — a deleted creator's link should keep working for the people already playing it.
CREATE TABLE challenges (
    id              varchar(16) PRIMARY KEY,
    asset_id        bigint NOT NULL REFERENCES assets (id),
    timeframe       varchar(255) NOT NULL,
    start_index     integer NOT NULL,
    creator_id      bigint REFERENCES users (id) ON DELETE SET NULL,
    creator_name    varchar(64) NOT NULL,
    creator_correct integer NOT NULL,
    total_guesses   integer NOT NULL,
    created_at      timestamp(6) with time zone NOT NULL,
    CONSTRAINT ck_challenges_score CHECK (creator_correct BETWEEN 0 AND total_guesses)
);

-- A signed-in creator asking twice for the same chart gets the same link back.
CREATE INDEX idx_challenges_creator_chart ON challenges (creator_id, asset_id, timeframe, start_index);

-- A signed-in player's guesses on a challenge, one row per guess, exactly like guess_results —
-- and deliberately NOT in guess_results. The creator has seen this chart's answers, so a
-- challenge is a chart whose answers somebody already knows; counted towards score, the
-- leaderboard, badges or retention, a second account could farm points off links its first
-- account made. A table of its own is how nothing that reads guess_results can see these, the
-- same separation pattern_quiz_results makes and for a similar reason.
--
-- The unique constraint is the one-attempt rule, as it is for the daily.
CREATE TABLE challenge_guesses (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    challenge_id      varchar(16) NOT NULL REFERENCES challenges (id) ON DELETE CASCADE,
    user_id           bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    guess_number      integer NOT NULL,
    guessed_direction varchar(8) CHECK (guessed_direction IN ('LONG', 'SHORT')),
    actual_direction  varchar(8) NOT NULL CHECK (actual_direction IN ('LONG', 'SHORT')),
    correct           boolean NOT NULL,
    created_at        timestamp(6) with time zone NOT NULL,
    CONSTRAINT uq_challenge_guesses_attempt UNIQUE (challenge_id, user_id, guess_number)
);
