-- One row per message the bot has posted to a Telegram group: which chat, which of the day's two
-- messages, which UTC day.
--
-- Not a log. It exists for its unique constraint: the row is written BEFORE the message is sent,
-- so a second instance running the same schedule (Render keeps the old one alive through a
-- deploy), a restart inside the scheduled minute or an admin pressing "send now" twice cannot
-- post the same announcement to a group twice. The cost of that order is the opposite failure —
-- a crash between the insert and the send loses one message — and a group missing one reminder
-- is the better of the two. A send that fails outright removes its row, so it can be retried.
CREATE TABLE telegram_broadcasts (
    id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id  bigint NOT NULL,
    kind     varchar(16) NOT NULL CHECK (kind IN ('MORNING', 'EVENING')),
    day      date NOT NULL,
    sent_at  timestamp(6) with time zone NOT NULL,
    CONSTRAINT uq_telegram_broadcasts UNIQUE (chat_id, kind, day)
);
