-- Baseline: the schema Hibernate's ddl-auto:update had been growing until now, written out
-- so a fresh database gets exactly what the existing ones already have. Constraint names are
-- spelled out here rather than left to Hibernate — a later migration that has to drop one
-- should not have to quote "uk9er8f1lva7e81sy29lb0uqpw".

CREATE TABLE assets (
    id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol varchar(255) NOT NULL,
    name   varchar(255) NOT NULL,
    type   varchar(255) NOT NULL CHECK (type IN ('CRYPTO', 'METAL')),
    CONSTRAINT uq_assets_symbol UNIQUE (symbol)
);

CREATE TABLE candles (
    id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id  bigint NOT NULL,
    timeframe varchar(255) NOT NULL,
    open_time timestamp(6) with time zone NOT NULL,
    open      numeric(20, 8) NOT NULL,
    high      numeric(20, 8) NOT NULL,
    low       numeric(20, 8) NOT NULL,
    close     numeric(20, 8) NOT NULL,
    volume    numeric(24, 8) NOT NULL,
    CONSTRAINT fk_candles_asset FOREIGN KEY (asset_id) REFERENCES assets (id),
    -- Also the index every round selection reads: the window query filters on asset and
    -- timeframe, then pages through open_time in order.
    CONSTRAINT uq_candles_asset_timeframe_open_time UNIQUE (asset_id, timeframe, open_time)
);

CREATE TABLE users (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_address     varchar(42) NOT NULL,
    display_name       varchar(100) NOT NULL,
    created_at         timestamp(6) with time zone NOT NULL,
    -- Tally carried over from a browser that played before signing in. Nullable: an account
    -- that never imported anything has no numbers here, which is different from zero.
    legacy_total       bigint,
    legacy_correct     bigint,
    legacy_score       bigint,
    legacy_best_streak integer,
    legacy_imported_at timestamp(6) with time zone,
    -- Bumped on logout to invalidate every refresh token issued so far.
    token_version      integer,
    CONSTRAINT uq_users_wallet_address UNIQUE (wallet_address)
);

CREATE TABLE guess_results (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           bigint NOT NULL,
    asset_id          bigint NOT NULL,
    timeframe         varchar(255) NOT NULL,
    start_index       integer NOT NULL,
    guess_number      integer NOT NULL,
    guessed_direction varchar(8) NOT NULL CHECK (guessed_direction IN ('LONG', 'SHORT')),
    actual_direction  varchar(8) NOT NULL CHECK (actual_direction IN ('LONG', 'SHORT')),
    correct           boolean NOT NULL,
    created_at        timestamp(6) with time zone NOT NULL,
    CONSTRAINT fk_guess_results_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_guess_results_asset FOREIGN KEY (asset_id) REFERENCES assets (id),
    -- One row per guess: replaying the same token must not tally twice.
    CONSTRAINT uq_guess_results_round_guess
        UNIQUE (user_id, asset_id, timeframe, start_index, guess_number)
);

CREATE INDEX idx_guess_results_user_time ON guess_results (user_id, created_at);
