-- What has failed lately, kept across restarts.
--
-- The ops pane used to read this out of a deque in memory: it answered "is something failing right
-- now", and it was emptied by every deploy — which on Render is also every night the free instance
-- is restarted. So the one question it could not answer was "what happened while nobody was
-- looking", which is the question the first evening on this host actually needed.
--
-- Rows are events, not derived state, so storing them invents no second source of truth: nothing
-- else in the app knows an error happened. Repeats of one failure fold into a row with a count
-- (an exchange ban raises the same error on every poll of every open tab), and a retention job
-- trims the table, because a log nobody deletes is a table that only grows.
CREATE TABLE app_errors (
    id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source   varchar(32) NOT NULL,
    where_at varchar(200) NOT NULL,
    summary  varchar(300) NOT NULL,
    first_at timestamp(6) with time zone NOT NULL,
    last_at  timestamp(6) with time zone NOT NULL,
    count    integer NOT NULL
);

-- The pane reads the newest rows and nothing else, and the retention job deletes by age.
CREATE INDEX idx_app_errors_last_at ON app_errors (last_at DESC, id DESC);
