-- The last of the content that lived in JavaScript: 13 candlestick patterns, 16 chart
-- patterns and 12 trading-psychology notes. Same treatment as blog_posts — a few columns
-- worth querying, and the item itself in jsonb, because the three kinds have three shapes
-- (patterns carry an illustration as candles, chart patterns as points, notes carry neither)
-- and one table modelling all three would be mostly null columns.
--
-- item_key is the "id" the JavaScript used. For the two pattern kinds it is not a label: it
-- is the join to a matcher in PatternLibrary / TechnicalPatternLibrary, which is Java. Rename
-- one and "Tìm ví dụ thật" starts asking the server to scan for a pattern that does not
-- exist, so the API refuses to create, delete or re-key those two kinds. Psychology notes
-- have no code behind them and are fully editable.
CREATE TABLE content_items (
    kind       varchar(24) NOT NULL
                   CHECK (kind IN ('CANDLE_PATTERN', 'TECHNICAL_PATTERN', 'PSYCHOLOGY')),
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_key   varchar(80) NOT NULL,
    -- Duplicated out of body so the admin list and the ordering do not have to open the jsonb.
    title      varchar(300) NOT NULL,
    body       jsonb NOT NULL DEFAULT '{}'::jsonb,
    position   integer NOT NULL DEFAULT 0,
    published  boolean NOT NULL DEFAULT true,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT uq_content_items_kind_key UNIQUE (kind, item_key)
);

-- Every public read is "this kind, published, in order".
CREATE INDEX idx_content_items_kind_published ON content_items (kind, published, position);
